//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exodus.WebServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExodusPrototype1Entities : DbContext
    {
        public ExodusPrototype1Entities()
            : base("name=ExodusPrototype1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DigitalWall> DigitalWalls { get; set; }
        public virtual DbSet<PhysicalWall> PhysicalWalls { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<SourceInstance> SourceInstances { get; set; }
        public virtual DbSet<SpaceSession> SpaceSessions { get; set; }
        public virtual DbSet<Wall> Walls { get; set; }
    }
}
