//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exodus.WebServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceSession
    {
        public int Id { get; set; }
        public int DigitalWallId { get; set; }
    
        public virtual DigitalWall DigitalWall { get; set; }
        public virtual Session Session { get; set; }
    }
}
